//! Renders `docs/site/guide/tools.md` from the built-in tool specs.
//!
//! The page shows each tool exactly as the engine publishes it to the model.
//! Regenerate it after changing a tool's name, description, or parameters:
//! `COOKIE_UPDATE_TOOL_DOCS=1 cargo test -p cookie_agent_tools tool_reference`.

use std::fmt::Write as _;

use cookie_agent_engine::{SessionToolContext, ToolProvider, ToolSpec};
use cookie_agent_protocol::SessionId;
use serde_json::Value;

use crate::{
    BuiltinTools, delegate::DelegateToolProvider, goal::GoalTools, message::MessageToolProvider,
    skill::SkillTool,
};

const DOC_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../docs/site/guide/tools.md"
);
const UPDATE_ENV: &str = "COOKIE_UPDATE_TOOL_DOCS";
/// Stands in for the session-specific `agent_type` enum of `delegate_subagent`.
const DELEGATE_TARGET_PLACEHOLDER: &str = "<subagent id>";

/// Every built-in tool, in the order the reference lists them.
fn documented_specs() -> Vec<ToolSpec> {
    let mut specs = BuiltinTools::new(std::env::temp_dir())
        .tools_for_session(&SessionToolContext::new(SessionId::new_v7()))
        .expect("built-in tool specs");
    specs.push(SkillTool::spec());
    specs.extend(DelegateToolProvider::specs(&[DELEGATE_TARGET_PLACEHOLDER]));
    specs.push(MessageToolProvider::spec());
    specs.push(GoalTools::get_spec());
    specs.push(GoalTools::update_spec());
    specs
}

/// When the engine publishes a tool, beyond a visible permission.
fn availability(name: &str) -> Option<&'static str> {
    Some(match name {
        "skill" => "Only when at least one skill is visible to the session.",
        "delegate_subagent" => {
            "Only when the agent can delegate to at least one subagent at this depth. The \
             `agent_type` enum lists those subagents; this page shows a placeholder."
        }
        "get_subagent_result" | "cancel_subagent" => {
            "Only when the agent can delegate to at least one subagent at this depth."
        }
        "goal_get" | "goal_update" => {
            "Only in a root session whose goal is active or paused when the run starts."
        }
        _ => return None,
    })
}

fn render(specs: &[ToolSpec]) -> String {
    let mut page = String::from(
        "<!-- Generated by crates/tools/src/tool_reference.rs. Do not edit by hand; regenerate with\n\
         COOKIE_UPDATE_TOOL_DOCS=1 cargo test -p cookie_agent_tools tool_reference -->\n\n\
         # Tools\n\n\
         This page shows each built-in tool exactly as Cookie Agent sends it to the model:\n\
         its name, its description, and the JSON Schema of its parameters. Provider adapters\n\
         place these three fields in their own request format but do not rewrite them.\n\n\
         A tool is sent only when the active agent has an `allow` or `ask` rule for the\n\
         tool's permission. Some tools have further conditions, noted under each tool.\n\
         MCP and plugin tools are described by their servers and plugins, not here.\n\n\
         To see which tools a real session sent with its latest request, expand the tools\n\
         block under the system prompt in the TUI transcript.\n\n\
         | Tool | Permission |\n|---|---|\n",
    );
    for spec in specs {
        writeln!(
            page,
            "| [`{0}`](#{0}) | `{1}` |",
            spec.name, spec.permission_name
        )
        .unwrap();
    }
    for spec in specs {
        render_tool(&mut page, spec);
    }
    page
}

fn render_tool(page: &mut String, spec: &ToolSpec) {
    let schema = &spec.parameters;
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|names| names.iter().filter_map(Value::as_str).collect::<Vec<_>>())
        .unwrap_or_default();

    let signature = properties
        .iter()
        .map(|(name, property)| {
            let optional = if required.contains(&name.as_str()) {
                ""
            } else {
                "?"
            };
            format!("{name}{optional}: {}", type_label(schema, property))
        })
        .collect::<Vec<_>>()
        .join(", ");
    write!(
        page,
        "\n## `{0}`\n\n```text\n{0}({signature})\n```\n\nDescription sent to the model:\n\n```text\n{1}\n```\n",
        spec.name, spec.description
    )
    .unwrap();
    if let Some(note) = availability(&spec.name) {
        write!(page, "\n{note}\n").unwrap();
    }
    if !properties.is_empty() {
        page.push_str("\n| Parameter | Type | Required | Description |\n|---|---|---|---|\n");
        for (name, property) in &properties {
            let resolved = resolve(schema, property);
            let mut description = resolved
                .get("description")
                .or_else(|| property.get("description"))
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_owned();
            if let Some(default) = property.get("default").or_else(|| resolved.get("default")) {
                if !description.is_empty() {
                    description.push(' ');
                }
                write!(description, "Default: `{default}`.").unwrap();
            }
            writeln!(
                page,
                "| `{name}` | `{}` | {} | {} |",
                type_label(schema, property).replace('|', "\\|"),
                if required.contains(&name.as_str()) {
                    "yes"
                } else {
                    "no"
                },
                description.replace('|', "\\|").replace('\n', " "),
            )
            .unwrap();
        }
    }
    let json = serde_json::to_string_pretty(schema).expect("schema serializes");
    page.push_str("\n??? note \"Parameters JSON Schema\"\n\n    ```json\n");
    for line in json.lines() {
        writeln!(page, "    {line}").unwrap();
    }
    page.push_str("    ```\n");
}

/// Follows a local `$ref` into `$defs` or `definitions`.
fn resolve<'a>(root: &'a Value, property: &'a Value) -> &'a Value {
    property
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|reference| reference.strip_prefix('#'))
        .and_then(|pointer| root.pointer(pointer))
        .unwrap_or(property)
}

fn type_label(root: &Value, property: &Value) -> String {
    let property = resolve(root, property);
    if let Some(values) = property.get("enum").and_then(Value::as_array) {
        return values
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    for key in ["anyOf", "oneOf"] {
        if let Some(variants) = property.get(key).and_then(Value::as_array) {
            let labels = variants
                .iter()
                .map(|variant| type_label(root, variant))
                .filter(|label| label != "null")
                .collect::<Vec<_>>();
            return labels.join(" | ");
        }
    }
    let types = match property.get("type") {
        Some(Value::String(name)) => vec![name.as_str()],
        Some(Value::Array(names)) => names
            .iter()
            .filter_map(Value::as_str)
            .filter(|name| *name != "null")
            .collect(),
        _ => return "any".into(),
    };
    types
        .into_iter()
        .map(|name| match name {
            "array" => format!(
                "{}[]",
                property
                    .get("items")
                    .map_or_else(|| "any".into(), |items| type_label(root, items))
            ),
            other => other.to_owned(),
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

#[test]
fn tool_reference_page_matches_published_specs() {
    let rendered = render(&documented_specs());
    if std::env::var_os(UPDATE_ENV).is_some() {
        std::fs::write(DOC_PATH, &rendered).expect("write tool reference");
        return;
    }
    let current = std::fs::read_to_string(DOC_PATH).unwrap_or_default();
    assert!(
        current == rendered,
        "docs/site/guide/tools.md is stale; regenerate with \
         {UPDATE_ENV}=1 cargo test -p cookie_agent_tools tool_reference"
    );
}
