[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
hosting = "github"
packages = ["cookie_agent"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]
installers = ["shell", "powershell"]
windows-archive = ".zip"
checksum = "sha256"
pr-run-mode = "plan"
install-path = "CARGO_HOME"
github-attestations = false
precise-builds = true
allow-dirty = ["ci"]
release-branch = "main"

[dist.binaries]
"*" = ["cookie"]

[dist.github-action-commits]
"actions/checkout" = "11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
"actions/upload-artifact" = "ea165f8d65b6e75b540449e92b4886f43607fa02" # v4.6.2
"actions/download-artifact" = "d3f86a106a0bac45b974a628896c90dbdf5c8093" # v4.3.0
"swatinem/rust-cache" = "6323deb102c322ba6fcbdcafc7e3dddab59af2b6" # v2.9.2

[dist.github-custom-runners]
"aarch64-pc-windows-msvc" = "windows-11-arm"
