[package]
name = "cookie_agent_config"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cookie_agent_models = { version = "=0.1.0", path = "../models" }
figment.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
insta.workspace = true
oven-sdk.workspace = true
serde_json.workspace = true
tempfile.workspace = true
