[package]
name = "cookie_agent_protocol"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cookie_agent_identity = { version = "=0.1.0", path = "../identity" }
jiff.workspace = true
oven-sdk.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ts-rs = { workspace = true, features = ["no-serde-warnings"] }
uuid.workspace = true

[dev-dependencies]
insta.workspace = true
